# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: JosiahDahl.com
header_title: Josiah Dahl
email: josiah.dahl@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The portfolio of Josiah Dahl. Web developer. Canadian, but living in America. I love a challenge and I love to
  learn new things!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.josiahdahl.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  josiahdahl
bitbucket_username: jodahl

# Build settings
markdown: kramdown

# Content URLS

# Collections
collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/

exclude: [node_modules/, raw_images/, bower_components/, gulpfile.js, bower.json, npm-debug.log, package.json]